### ISSUE TITLE
V2 API compatibility broken?

### ISSUE THREAD

**Issue by tdegouw** [jbaragry/ardoq-python-client#6]
When using the library in V2 mode

```
    ardoq = ArdoqClient(hosturl='https://xxxx.ardoq.com', token='xxxx', version='v2')
    print(ardoq.get_workspaces(summary=True))
    print(ardoq.get_models())
```
Both these base calls raise an ArdoqClientException when using the V2 API.

`ardoqpy.ardoqpy.ArdoqClientException: {'code': 404, 'reason': 'Not Found', 'text': 'Not found'}`

**Comment by jbaragry** [comment]
thanks. I'll have a look

**Comment by jbaragry** [comment]
fixed and updated in pypi
